project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Kaixing Liu"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme:
      light: sandstone
      dark: slate
    css: styles.css
    toc: true
    page-layout: full

editor: visual

